package org.generation.italy.ProjectPEPE.model.entities.enums;

public enum Category {
    REDMEAT,WHITEMEAT,FATFISH,THINFISH,EGG,DAIRY,CHEESE,CEREAL,TUBER,VEGETABLE,FRUIT,DRYFRUIT,SEASONINGFAT,SPICE
}